repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
        args: ["-l", "89"]

-   repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        args:
        -   "--max-line-length"
        -   "89"
        -   "--exclude"
        -   "modules/timeparse.py"
        -   "--ignore"
        -   "E201,E202,E203,W503"
